package com.chu.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SiteConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    public SiteConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSiteNameIsNull() {
            addCriterion("site_name is null");
            return (Criteria) this;
        }

        public Criteria andSiteNameIsNotNull() {
            addCriterion("site_name is not null");
            return (Criteria) this;
        }

        public Criteria andSiteNameEqualTo(String value) {
            addCriterion("site_name =", value, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameNotEqualTo(String value) {
            addCriterion("site_name <>", value, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameGreaterThan(String value) {
            addCriterion("site_name >", value, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameGreaterThanOrEqualTo(String value) {
            addCriterion("site_name >=", value, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameLessThan(String value) {
            addCriterion("site_name <", value, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameLessThanOrEqualTo(String value) {
            addCriterion("site_name <=", value, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameLike(String value) {
            addCriterion("site_name like", value, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameNotLike(String value) {
            addCriterion("site_name not like", value, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameIn(List<String> values) {
            addCriterion("site_name in", values, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameNotIn(List<String> values) {
            addCriterion("site_name not in", values, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameBetween(String value1, String value2) {
            addCriterion("site_name between", value1, value2, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameNotBetween(String value1, String value2) {
            addCriterion("site_name not between", value1, value2, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteAddressIsNull() {
            addCriterion("site_address is null");
            return (Criteria) this;
        }

        public Criteria andSiteAddressIsNotNull() {
            addCriterion("site_address is not null");
            return (Criteria) this;
        }

        public Criteria andSiteAddressEqualTo(String value) {
            addCriterion("site_address =", value, "siteAddress");
            return (Criteria) this;
        }

        public Criteria andSiteAddressNotEqualTo(String value) {
            addCriterion("site_address <>", value, "siteAddress");
            return (Criteria) this;
        }

        public Criteria andSiteAddressGreaterThan(String value) {
            addCriterion("site_address >", value, "siteAddress");
            return (Criteria) this;
        }

        public Criteria andSiteAddressGreaterThanOrEqualTo(String value) {
            addCriterion("site_address >=", value, "siteAddress");
            return (Criteria) this;
        }

        public Criteria andSiteAddressLessThan(String value) {
            addCriterion("site_address <", value, "siteAddress");
            return (Criteria) this;
        }

        public Criteria andSiteAddressLessThanOrEqualTo(String value) {
            addCriterion("site_address <=", value, "siteAddress");
            return (Criteria) this;
        }

        public Criteria andSiteAddressLike(String value) {
            addCriterion("site_address like", value, "siteAddress");
            return (Criteria) this;
        }

        public Criteria andSiteAddressNotLike(String value) {
            addCriterion("site_address not like", value, "siteAddress");
            return (Criteria) this;
        }

        public Criteria andSiteAddressIn(List<String> values) {
            addCriterion("site_address in", values, "siteAddress");
            return (Criteria) this;
        }

        public Criteria andSiteAddressNotIn(List<String> values) {
            addCriterion("site_address not in", values, "siteAddress");
            return (Criteria) this;
        }

        public Criteria andSiteAddressBetween(String value1, String value2) {
            addCriterion("site_address between", value1, value2, "siteAddress");
            return (Criteria) this;
        }

        public Criteria andSiteAddressNotBetween(String value1, String value2) {
            addCriterion("site_address not between", value1, value2, "siteAddress");
            return (Criteria) this;
        }

        public Criteria andSiteIntroIsNull() {
            addCriterion("site_intro is null");
            return (Criteria) this;
        }

        public Criteria andSiteIntroIsNotNull() {
            addCriterion("site_intro is not null");
            return (Criteria) this;
        }

        public Criteria andSiteIntroEqualTo(String value) {
            addCriterion("site_intro =", value, "siteIntro");
            return (Criteria) this;
        }

        public Criteria andSiteIntroNotEqualTo(String value) {
            addCriterion("site_intro <>", value, "siteIntro");
            return (Criteria) this;
        }

        public Criteria andSiteIntroGreaterThan(String value) {
            addCriterion("site_intro >", value, "siteIntro");
            return (Criteria) this;
        }

        public Criteria andSiteIntroGreaterThanOrEqualTo(String value) {
            addCriterion("site_intro >=", value, "siteIntro");
            return (Criteria) this;
        }

        public Criteria andSiteIntroLessThan(String value) {
            addCriterion("site_intro <", value, "siteIntro");
            return (Criteria) this;
        }

        public Criteria andSiteIntroLessThanOrEqualTo(String value) {
            addCriterion("site_intro <=", value, "siteIntro");
            return (Criteria) this;
        }

        public Criteria andSiteIntroLike(String value) {
            addCriterion("site_intro like", value, "siteIntro");
            return (Criteria) this;
        }

        public Criteria andSiteIntroNotLike(String value) {
            addCriterion("site_intro not like", value, "siteIntro");
            return (Criteria) this;
        }

        public Criteria andSiteIntroIn(List<String> values) {
            addCriterion("site_intro in", values, "siteIntro");
            return (Criteria) this;
        }

        public Criteria andSiteIntroNotIn(List<String> values) {
            addCriterion("site_intro not in", values, "siteIntro");
            return (Criteria) this;
        }

        public Criteria andSiteIntroBetween(String value1, String value2) {
            addCriterion("site_intro between", value1, value2, "siteIntro");
            return (Criteria) this;
        }

        public Criteria andSiteIntroNotBetween(String value1, String value2) {
            addCriterion("site_intro not between", value1, value2, "siteIntro");
            return (Criteria) this;
        }

        public Criteria andSiteNoticeIsNull() {
            addCriterion("site_notice is null");
            return (Criteria) this;
        }

        public Criteria andSiteNoticeIsNotNull() {
            addCriterion("site_notice is not null");
            return (Criteria) this;
        }

        public Criteria andSiteNoticeEqualTo(String value) {
            addCriterion("site_notice =", value, "siteNotice");
            return (Criteria) this;
        }

        public Criteria andSiteNoticeNotEqualTo(String value) {
            addCriterion("site_notice <>", value, "siteNotice");
            return (Criteria) this;
        }

        public Criteria andSiteNoticeGreaterThan(String value) {
            addCriterion("site_notice >", value, "siteNotice");
            return (Criteria) this;
        }

        public Criteria andSiteNoticeGreaterThanOrEqualTo(String value) {
            addCriterion("site_notice >=", value, "siteNotice");
            return (Criteria) this;
        }

        public Criteria andSiteNoticeLessThan(String value) {
            addCriterion("site_notice <", value, "siteNotice");
            return (Criteria) this;
        }

        public Criteria andSiteNoticeLessThanOrEqualTo(String value) {
            addCriterion("site_notice <=", value, "siteNotice");
            return (Criteria) this;
        }

        public Criteria andSiteNoticeLike(String value) {
            addCriterion("site_notice like", value, "siteNotice");
            return (Criteria) this;
        }

        public Criteria andSiteNoticeNotLike(String value) {
            addCriterion("site_notice not like", value, "siteNotice");
            return (Criteria) this;
        }

        public Criteria andSiteNoticeIn(List<String> values) {
            addCriterion("site_notice in", values, "siteNotice");
            return (Criteria) this;
        }

        public Criteria andSiteNoticeNotIn(List<String> values) {
            addCriterion("site_notice not in", values, "siteNotice");
            return (Criteria) this;
        }

        public Criteria andSiteNoticeBetween(String value1, String value2) {
            addCriterion("site_notice between", value1, value2, "siteNotice");
            return (Criteria) this;
        }

        public Criteria andSiteNoticeNotBetween(String value1, String value2) {
            addCriterion("site_notice not between", value1, value2, "siteNotice");
            return (Criteria) this;
        }

        public Criteria andCreateSiteTimeIsNull() {
            addCriterion("create_site_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateSiteTimeIsNotNull() {
            addCriterion("create_site_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateSiteTimeEqualTo(String value) {
            addCriterion("create_site_time =", value, "createSiteTime");
            return (Criteria) this;
        }

        public Criteria andCreateSiteTimeNotEqualTo(String value) {
            addCriterion("create_site_time <>", value, "createSiteTime");
            return (Criteria) this;
        }

        public Criteria andCreateSiteTimeGreaterThan(String value) {
            addCriterion("create_site_time >", value, "createSiteTime");
            return (Criteria) this;
        }

        public Criteria andCreateSiteTimeGreaterThanOrEqualTo(String value) {
            addCriterion("create_site_time >=", value, "createSiteTime");
            return (Criteria) this;
        }

        public Criteria andCreateSiteTimeLessThan(String value) {
            addCriterion("create_site_time <", value, "createSiteTime");
            return (Criteria) this;
        }

        public Criteria andCreateSiteTimeLessThanOrEqualTo(String value) {
            addCriterion("create_site_time <=", value, "createSiteTime");
            return (Criteria) this;
        }

        public Criteria andCreateSiteTimeLike(String value) {
            addCriterion("create_site_time like", value, "createSiteTime");
            return (Criteria) this;
        }

        public Criteria andCreateSiteTimeNotLike(String value) {
            addCriterion("create_site_time not like", value, "createSiteTime");
            return (Criteria) this;
        }

        public Criteria andCreateSiteTimeIn(List<String> values) {
            addCriterion("create_site_time in", values, "createSiteTime");
            return (Criteria) this;
        }

        public Criteria andCreateSiteTimeNotIn(List<String> values) {
            addCriterion("create_site_time not in", values, "createSiteTime");
            return (Criteria) this;
        }

        public Criteria andCreateSiteTimeBetween(String value1, String value2) {
            addCriterion("create_site_time between", value1, value2, "createSiteTime");
            return (Criteria) this;
        }

        public Criteria andCreateSiteTimeNotBetween(String value1, String value2) {
            addCriterion("create_site_time not between", value1, value2, "createSiteTime");
            return (Criteria) this;
        }

        public Criteria andRecordNumberIsNull() {
            addCriterion("record_number is null");
            return (Criteria) this;
        }

        public Criteria andRecordNumberIsNotNull() {
            addCriterion("record_number is not null");
            return (Criteria) this;
        }

        public Criteria andRecordNumberEqualTo(String value) {
            addCriterion("record_number =", value, "recordNumber");
            return (Criteria) this;
        }

        public Criteria andRecordNumberNotEqualTo(String value) {
            addCriterion("record_number <>", value, "recordNumber");
            return (Criteria) this;
        }

        public Criteria andRecordNumberGreaterThan(String value) {
            addCriterion("record_number >", value, "recordNumber");
            return (Criteria) this;
        }

        public Criteria andRecordNumberGreaterThanOrEqualTo(String value) {
            addCriterion("record_number >=", value, "recordNumber");
            return (Criteria) this;
        }

        public Criteria andRecordNumberLessThan(String value) {
            addCriterion("record_number <", value, "recordNumber");
            return (Criteria) this;
        }

        public Criteria andRecordNumberLessThanOrEqualTo(String value) {
            addCriterion("record_number <=", value, "recordNumber");
            return (Criteria) this;
        }

        public Criteria andRecordNumberLike(String value) {
            addCriterion("record_number like", value, "recordNumber");
            return (Criteria) this;
        }

        public Criteria andRecordNumberNotLike(String value) {
            addCriterion("record_number not like", value, "recordNumber");
            return (Criteria) this;
        }

        public Criteria andRecordNumberIn(List<String> values) {
            addCriterion("record_number in", values, "recordNumber");
            return (Criteria) this;
        }

        public Criteria andRecordNumberNotIn(List<String> values) {
            addCriterion("record_number not in", values, "recordNumber");
            return (Criteria) this;
        }

        public Criteria andRecordNumberBetween(String value1, String value2) {
            addCriterion("record_number between", value1, value2, "recordNumber");
            return (Criteria) this;
        }

        public Criteria andRecordNumberNotBetween(String value1, String value2) {
            addCriterion("record_number not between", value1, value2, "recordNumber");
            return (Criteria) this;
        }

        public Criteria andAuthorAvatarIsNull() {
            addCriterion("author_avatar is null");
            return (Criteria) this;
        }

        public Criteria andAuthorAvatarIsNotNull() {
            addCriterion("author_avatar is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorAvatarEqualTo(String value) {
            addCriterion("author_avatar =", value, "authorAvatar");
            return (Criteria) this;
        }

        public Criteria andAuthorAvatarNotEqualTo(String value) {
            addCriterion("author_avatar <>", value, "authorAvatar");
            return (Criteria) this;
        }

        public Criteria andAuthorAvatarGreaterThan(String value) {
            addCriterion("author_avatar >", value, "authorAvatar");
            return (Criteria) this;
        }

        public Criteria andAuthorAvatarGreaterThanOrEqualTo(String value) {
            addCriterion("author_avatar >=", value, "authorAvatar");
            return (Criteria) this;
        }

        public Criteria andAuthorAvatarLessThan(String value) {
            addCriterion("author_avatar <", value, "authorAvatar");
            return (Criteria) this;
        }

        public Criteria andAuthorAvatarLessThanOrEqualTo(String value) {
            addCriterion("author_avatar <=", value, "authorAvatar");
            return (Criteria) this;
        }

        public Criteria andAuthorAvatarLike(String value) {
            addCriterion("author_avatar like", value, "authorAvatar");
            return (Criteria) this;
        }

        public Criteria andAuthorAvatarNotLike(String value) {
            addCriterion("author_avatar not like", value, "authorAvatar");
            return (Criteria) this;
        }

        public Criteria andAuthorAvatarIn(List<String> values) {
            addCriterion("author_avatar in", values, "authorAvatar");
            return (Criteria) this;
        }

        public Criteria andAuthorAvatarNotIn(List<String> values) {
            addCriterion("author_avatar not in", values, "authorAvatar");
            return (Criteria) this;
        }

        public Criteria andAuthorAvatarBetween(String value1, String value2) {
            addCriterion("author_avatar between", value1, value2, "authorAvatar");
            return (Criteria) this;
        }

        public Criteria andAuthorAvatarNotBetween(String value1, String value2) {
            addCriterion("author_avatar not between", value1, value2, "authorAvatar");
            return (Criteria) this;
        }

        public Criteria andTouristAvatarIsNull() {
            addCriterion("tourist_avatar is null");
            return (Criteria) this;
        }

        public Criteria andTouristAvatarIsNotNull() {
            addCriterion("tourist_avatar is not null");
            return (Criteria) this;
        }

        public Criteria andTouristAvatarEqualTo(String value) {
            addCriterion("tourist_avatar =", value, "touristAvatar");
            return (Criteria) this;
        }

        public Criteria andTouristAvatarNotEqualTo(String value) {
            addCriterion("tourist_avatar <>", value, "touristAvatar");
            return (Criteria) this;
        }

        public Criteria andTouristAvatarGreaterThan(String value) {
            addCriterion("tourist_avatar >", value, "touristAvatar");
            return (Criteria) this;
        }

        public Criteria andTouristAvatarGreaterThanOrEqualTo(String value) {
            addCriterion("tourist_avatar >=", value, "touristAvatar");
            return (Criteria) this;
        }

        public Criteria andTouristAvatarLessThan(String value) {
            addCriterion("tourist_avatar <", value, "touristAvatar");
            return (Criteria) this;
        }

        public Criteria andTouristAvatarLessThanOrEqualTo(String value) {
            addCriterion("tourist_avatar <=", value, "touristAvatar");
            return (Criteria) this;
        }

        public Criteria andTouristAvatarLike(String value) {
            addCriterion("tourist_avatar like", value, "touristAvatar");
            return (Criteria) this;
        }

        public Criteria andTouristAvatarNotLike(String value) {
            addCriterion("tourist_avatar not like", value, "touristAvatar");
            return (Criteria) this;
        }

        public Criteria andTouristAvatarIn(List<String> values) {
            addCriterion("tourist_avatar in", values, "touristAvatar");
            return (Criteria) this;
        }

        public Criteria andTouristAvatarNotIn(List<String> values) {
            addCriterion("tourist_avatar not in", values, "touristAvatar");
            return (Criteria) this;
        }

        public Criteria andTouristAvatarBetween(String value1, String value2) {
            addCriterion("tourist_avatar between", value1, value2, "touristAvatar");
            return (Criteria) this;
        }

        public Criteria andTouristAvatarNotBetween(String value1, String value2) {
            addCriterion("tourist_avatar not between", value1, value2, "touristAvatar");
            return (Criteria) this;
        }

        public Criteria andSiteAuthorIsNull() {
            addCriterion("site_author is null");
            return (Criteria) this;
        }

        public Criteria andSiteAuthorIsNotNull() {
            addCriterion("site_author is not null");
            return (Criteria) this;
        }

        public Criteria andSiteAuthorEqualTo(String value) {
            addCriterion("site_author =", value, "siteAuthor");
            return (Criteria) this;
        }

        public Criteria andSiteAuthorNotEqualTo(String value) {
            addCriterion("site_author <>", value, "siteAuthor");
            return (Criteria) this;
        }

        public Criteria andSiteAuthorGreaterThan(String value) {
            addCriterion("site_author >", value, "siteAuthor");
            return (Criteria) this;
        }

        public Criteria andSiteAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("site_author >=", value, "siteAuthor");
            return (Criteria) this;
        }

        public Criteria andSiteAuthorLessThan(String value) {
            addCriterion("site_author <", value, "siteAuthor");
            return (Criteria) this;
        }

        public Criteria andSiteAuthorLessThanOrEqualTo(String value) {
            addCriterion("site_author <=", value, "siteAuthor");
            return (Criteria) this;
        }

        public Criteria andSiteAuthorLike(String value) {
            addCriterion("site_author like", value, "siteAuthor");
            return (Criteria) this;
        }

        public Criteria andSiteAuthorNotLike(String value) {
            addCriterion("site_author not like", value, "siteAuthor");
            return (Criteria) this;
        }

        public Criteria andSiteAuthorIn(List<String> values) {
            addCriterion("site_author in", values, "siteAuthor");
            return (Criteria) this;
        }

        public Criteria andSiteAuthorNotIn(List<String> values) {
            addCriterion("site_author not in", values, "siteAuthor");
            return (Criteria) this;
        }

        public Criteria andSiteAuthorBetween(String value1, String value2) {
            addCriterion("site_author between", value1, value2, "siteAuthor");
            return (Criteria) this;
        }

        public Criteria andSiteAuthorNotBetween(String value1, String value2) {
            addCriterion("site_author not between", value1, value2, "siteAuthor");
            return (Criteria) this;
        }

        public Criteria andArticleCoverIsNull() {
            addCriterion("article_cover is null");
            return (Criteria) this;
        }

        public Criteria andArticleCoverIsNotNull() {
            addCriterion("article_cover is not null");
            return (Criteria) this;
        }

        public Criteria andArticleCoverEqualTo(String value) {
            addCriterion("article_cover =", value, "articleCover");
            return (Criteria) this;
        }

        public Criteria andArticleCoverNotEqualTo(String value) {
            addCriterion("article_cover <>", value, "articleCover");
            return (Criteria) this;
        }

        public Criteria andArticleCoverGreaterThan(String value) {
            addCriterion("article_cover >", value, "articleCover");
            return (Criteria) this;
        }

        public Criteria andArticleCoverGreaterThanOrEqualTo(String value) {
            addCriterion("article_cover >=", value, "articleCover");
            return (Criteria) this;
        }

        public Criteria andArticleCoverLessThan(String value) {
            addCriterion("article_cover <", value, "articleCover");
            return (Criteria) this;
        }

        public Criteria andArticleCoverLessThanOrEqualTo(String value) {
            addCriterion("article_cover <=", value, "articleCover");
            return (Criteria) this;
        }

        public Criteria andArticleCoverLike(String value) {
            addCriterion("article_cover like", value, "articleCover");
            return (Criteria) this;
        }

        public Criteria andArticleCoverNotLike(String value) {
            addCriterion("article_cover not like", value, "articleCover");
            return (Criteria) this;
        }

        public Criteria andArticleCoverIn(List<String> values) {
            addCriterion("article_cover in", values, "articleCover");
            return (Criteria) this;
        }

        public Criteria andArticleCoverNotIn(List<String> values) {
            addCriterion("article_cover not in", values, "articleCover");
            return (Criteria) this;
        }

        public Criteria andArticleCoverBetween(String value1, String value2) {
            addCriterion("article_cover between", value1, value2, "articleCover");
            return (Criteria) this;
        }

        public Criteria andArticleCoverNotBetween(String value1, String value2) {
            addCriterion("article_cover not between", value1, value2, "articleCover");
            return (Criteria) this;
        }

        public Criteria andGithubIsNull() {
            addCriterion("github is null");
            return (Criteria) this;
        }

        public Criteria andGithubIsNotNull() {
            addCriterion("github is not null");
            return (Criteria) this;
        }

        public Criteria andGithubEqualTo(String value) {
            addCriterion("github =", value, "github");
            return (Criteria) this;
        }

        public Criteria andGithubNotEqualTo(String value) {
            addCriterion("github <>", value, "github");
            return (Criteria) this;
        }

        public Criteria andGithubGreaterThan(String value) {
            addCriterion("github >", value, "github");
            return (Criteria) this;
        }

        public Criteria andGithubGreaterThanOrEqualTo(String value) {
            addCriterion("github >=", value, "github");
            return (Criteria) this;
        }

        public Criteria andGithubLessThan(String value) {
            addCriterion("github <", value, "github");
            return (Criteria) this;
        }

        public Criteria andGithubLessThanOrEqualTo(String value) {
            addCriterion("github <=", value, "github");
            return (Criteria) this;
        }

        public Criteria andGithubLike(String value) {
            addCriterion("github like", value, "github");
            return (Criteria) this;
        }

        public Criteria andGithubNotLike(String value) {
            addCriterion("github not like", value, "github");
            return (Criteria) this;
        }

        public Criteria andGithubIn(List<String> values) {
            addCriterion("github in", values, "github");
            return (Criteria) this;
        }

        public Criteria andGithubNotIn(List<String> values) {
            addCriterion("github not in", values, "github");
            return (Criteria) this;
        }

        public Criteria andGithubBetween(String value1, String value2) {
            addCriterion("github between", value1, value2, "github");
            return (Criteria) this;
        }

        public Criteria andGithubNotBetween(String value1, String value2) {
            addCriterion("github not between", value1, value2, "github");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andCommentCheckIsNull() {
            addCriterion("comment_check is null");
            return (Criteria) this;
        }

        public Criteria andCommentCheckIsNotNull() {
            addCriterion("comment_check is not null");
            return (Criteria) this;
        }

        public Criteria andCommentCheckEqualTo(Boolean value) {
            addCriterion("comment_check =", value, "commentCheck");
            return (Criteria) this;
        }

        public Criteria andCommentCheckNotEqualTo(Boolean value) {
            addCriterion("comment_check <>", value, "commentCheck");
            return (Criteria) this;
        }

        public Criteria andCommentCheckGreaterThan(Boolean value) {
            addCriterion("comment_check >", value, "commentCheck");
            return (Criteria) this;
        }

        public Criteria andCommentCheckGreaterThanOrEqualTo(Boolean value) {
            addCriterion("comment_check >=", value, "commentCheck");
            return (Criteria) this;
        }

        public Criteria andCommentCheckLessThan(Boolean value) {
            addCriterion("comment_check <", value, "commentCheck");
            return (Criteria) this;
        }

        public Criteria andCommentCheckLessThanOrEqualTo(Boolean value) {
            addCriterion("comment_check <=", value, "commentCheck");
            return (Criteria) this;
        }

        public Criteria andCommentCheckIn(List<Boolean> values) {
            addCriterion("comment_check in", values, "commentCheck");
            return (Criteria) this;
        }

        public Criteria andCommentCheckNotIn(List<Boolean> values) {
            addCriterion("comment_check not in", values, "commentCheck");
            return (Criteria) this;
        }

        public Criteria andCommentCheckBetween(Boolean value1, Boolean value2) {
            addCriterion("comment_check between", value1, value2, "commentCheck");
            return (Criteria) this;
        }

        public Criteria andCommentCheckNotBetween(Boolean value1, Boolean value2) {
            addCriterion("comment_check not between", value1, value2, "commentCheck");
            return (Criteria) this;
        }

        public Criteria andEmailNoticeIsNull() {
            addCriterion("email_notice is null");
            return (Criteria) this;
        }

        public Criteria andEmailNoticeIsNotNull() {
            addCriterion("email_notice is not null");
            return (Criteria) this;
        }

        public Criteria andEmailNoticeEqualTo(Boolean value) {
            addCriterion("email_notice =", value, "emailNotice");
            return (Criteria) this;
        }

        public Criteria andEmailNoticeNotEqualTo(Boolean value) {
            addCriterion("email_notice <>", value, "emailNotice");
            return (Criteria) this;
        }

        public Criteria andEmailNoticeGreaterThan(Boolean value) {
            addCriterion("email_notice >", value, "emailNotice");
            return (Criteria) this;
        }

        public Criteria andEmailNoticeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("email_notice >=", value, "emailNotice");
            return (Criteria) this;
        }

        public Criteria andEmailNoticeLessThan(Boolean value) {
            addCriterion("email_notice <", value, "emailNotice");
            return (Criteria) this;
        }

        public Criteria andEmailNoticeLessThanOrEqualTo(Boolean value) {
            addCriterion("email_notice <=", value, "emailNotice");
            return (Criteria) this;
        }

        public Criteria andEmailNoticeIn(List<Boolean> values) {
            addCriterion("email_notice in", values, "emailNotice");
            return (Criteria) this;
        }

        public Criteria andEmailNoticeNotIn(List<Boolean> values) {
            addCriterion("email_notice not in", values, "emailNotice");
            return (Criteria) this;
        }

        public Criteria andEmailNoticeBetween(Boolean value1, Boolean value2) {
            addCriterion("email_notice between", value1, value2, "emailNotice");
            return (Criteria) this;
        }

        public Criteria andEmailNoticeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("email_notice not between", value1, value2, "emailNotice");
            return (Criteria) this;
        }

        public Criteria andWebsocketUrlIsNull() {
            addCriterion("websocket_url is null");
            return (Criteria) this;
        }

        public Criteria andWebsocketUrlIsNotNull() {
            addCriterion("websocket_url is not null");
            return (Criteria) this;
        }

        public Criteria andWebsocketUrlEqualTo(String value) {
            addCriterion("websocket_url =", value, "websocketUrl");
            return (Criteria) this;
        }

        public Criteria andWebsocketUrlNotEqualTo(String value) {
            addCriterion("websocket_url <>", value, "websocketUrl");
            return (Criteria) this;
        }

        public Criteria andWebsocketUrlGreaterThan(String value) {
            addCriterion("websocket_url >", value, "websocketUrl");
            return (Criteria) this;
        }

        public Criteria andWebsocketUrlGreaterThanOrEqualTo(String value) {
            addCriterion("websocket_url >=", value, "websocketUrl");
            return (Criteria) this;
        }

        public Criteria andWebsocketUrlLessThan(String value) {
            addCriterion("websocket_url <", value, "websocketUrl");
            return (Criteria) this;
        }

        public Criteria andWebsocketUrlLessThanOrEqualTo(String value) {
            addCriterion("websocket_url <=", value, "websocketUrl");
            return (Criteria) this;
        }

        public Criteria andWebsocketUrlLike(String value) {
            addCriterion("websocket_url like", value, "websocketUrl");
            return (Criteria) this;
        }

        public Criteria andWebsocketUrlNotLike(String value) {
            addCriterion("websocket_url not like", value, "websocketUrl");
            return (Criteria) this;
        }

        public Criteria andWebsocketUrlIn(List<String> values) {
            addCriterion("websocket_url in", values, "websocketUrl");
            return (Criteria) this;
        }

        public Criteria andWebsocketUrlNotIn(List<String> values) {
            addCriterion("websocket_url not in", values, "websocketUrl");
            return (Criteria) this;
        }

        public Criteria andWebsocketUrlBetween(String value1, String value2) {
            addCriterion("websocket_url between", value1, value2, "websocketUrl");
            return (Criteria) this;
        }

        public Criteria andWebsocketUrlNotBetween(String value1, String value2) {
            addCriterion("websocket_url not between", value1, value2, "websocketUrl");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_site_config
     *
     * @mbggenerated do_not_delete_during_merge Sat Dec 23 12:18:10 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}