package com.chu.mapper;

import com.chu.entity.Album;
import com.chu.entity.AlbumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlbumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_album
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int countByExample(AlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_album
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_album
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int insert(Album record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_album
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int insertSelective(Album record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_album
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    List<Album> selectByExample(AlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_album
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    Album selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_album
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByExampleSelective(@Param("record") Album record, @Param("example") AlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_album
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByExample(@Param("record") Album record, @Param("example") AlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_album
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByPrimaryKeySelective(Album record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_album
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByPrimaryKey(Album record);
}