package com.chu.mapper;

import com.chu.entity.ArticleTag;
import com.chu.entity.ArticleTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_tag
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int countByExample(ArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_tag
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_tag
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int insert(ArticleTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_tag
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int insertSelective(ArticleTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_tag
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    List<ArticleTag> selectByExample(ArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_tag
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    ArticleTag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_tag
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByExampleSelective(@Param("record") ArticleTag record, @Param("example") ArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_tag
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByExample(@Param("record") ArticleTag record, @Param("example") ArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_tag
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByPrimaryKeySelective(ArticleTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_tag
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByPrimaryKey(ArticleTag record);
}