package com.chu.mapper;

import com.chu.entity.BlogFile;
import com.chu.entity.BlogFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlogFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_file
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int countByExample(BlogFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_file
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_file
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int insert(BlogFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_file
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int insertSelective(BlogFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_file
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    List<BlogFile> selectByExample(BlogFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_file
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    BlogFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_file
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByExampleSelective(@Param("record") BlogFile record, @Param("example") BlogFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_file
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByExample(@Param("record") BlogFile record, @Param("example") BlogFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_file
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByPrimaryKeySelective(BlogFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_file
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByPrimaryKey(BlogFile record);
}