package com.chu.mapper;

import com.chu.entity.SiteConfig;
import com.chu.entity.SiteConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SiteConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int countByExample(SiteConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int insert(SiteConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int insertSelective(SiteConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    List<SiteConfig> selectByExampleWithBLOBs(SiteConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    List<SiteConfig> selectByExample(SiteConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    SiteConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByExampleSelective(@Param("record") SiteConfig record, @Param("example") SiteConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") SiteConfig record, @Param("example") SiteConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByExample(@Param("record") SiteConfig record, @Param("example") SiteConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByPrimaryKeySelective(SiteConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(SiteConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_config
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByPrimaryKey(SiteConfig record);
}