package com.chu.mapper;

import com.chu.entity.TaskLog;
import com.chu.entity.TaskLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_log
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int countByExample(TaskLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_log
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_log
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int insert(TaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_log
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int insertSelective(TaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_log
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    List<TaskLog> selectByExampleWithBLOBs(TaskLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_log
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    List<TaskLog> selectByExample(TaskLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_log
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    TaskLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_log
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByExampleSelective(@Param("record") TaskLog record, @Param("example") TaskLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_log
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") TaskLog record, @Param("example") TaskLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_log
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByExample(@Param("record") TaskLog record, @Param("example") TaskLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_log
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByPrimaryKeySelective(TaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_log
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(TaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_log
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByPrimaryKey(TaskLog record);
}