package com.chu.mapper;

import com.chu.entity.VisitLog;
import com.chu.entity.VisitLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VisitLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_log
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int countByExample(VisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_log
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_log
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int insert(VisitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_log
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int insertSelective(VisitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_log
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    List<VisitLog> selectByExample(VisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_log
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    VisitLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_log
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByExampleSelective(@Param("record") VisitLog record, @Param("example") VisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_log
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByExample(@Param("record") VisitLog record, @Param("example") VisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_log
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByPrimaryKeySelective(VisitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_log
     *
     * @mbggenerated Sat Dec 23 12:18:10 CST 2023
     */
    int updateByPrimaryKey(VisitLog record);
}